#!/bin/sh
# Author: TuxCoder
# Date: 22-01-2015
#
# Script to generate basic config for gitlab

BASE=$(echo "dc=${DOMAIN}" | sed "s/\./,dc=/")


#gitlab-ctl reconfigure
chown 777 -R /var/opt/gitlab/
chown gitlab-psql:git -R /var/opt/gitlab/postgresql/
chmod og-rwx -R /var/opt/gitlab/postgresql/





cp /setup/gitlab.yml /var/opt/gitlab/gitlab-rails/etc/gitlab.yml

#replace placeholder in config
sed -i s/__DOMAIN__/${DOMAIN}/g                   /var/opt/gitlab/gitlab-rails/etc/gitlab.yml
sed -i s/__GIT_PASSWORD__/${LDAP_GIT_PASWORD}/g   /var/opt/gitlab/gitlab-rails/etc/gitlab.yml
sed -i s/__BASE__/${BASE}/g                       /var/opt/gitlab/gitlab-rails/etc/gitlab.yml

/opt/gitlab/embedded/bin/runsvdir-start &
sleep 10

gitlab-ctl start
